name: Build-Godot-CI
# on:
#   push:
#     tags:
#       - 'v*.*.*'
on: push
env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: auto-survival
  PROJECT_PATH: godot
jobs:
  build-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:mono-4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: .NET installation
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: Setup
        run: |
          ls -la
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates
          ls -la /root/.local/share/godot/templates/
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Copy export templates
        run: |
          ls -la
          ls -la ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
          # cp -r godot/export_templates ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Build
        run: |
          godot \
            -v \
            --headless \
            --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME_windows.exe \
            --path godot/ \
            --build-solutions
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./build/windows/
  upload:
    runs-on: ubuntu-latest
    needs: build-windows
    strategy:
      matrix:
        # platform: [linux, windows, mac]
        platform: [windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: ./build/${{ matrix.platform }}