name: Build-Godot

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    outputs:
      build_path: ${{ github.workspace }}/${{ steps.build_godot.outputs.build }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build_${{ matrix.platform }}.
        id: build_godot
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Client_${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build_godot.outputs.build }}
  upload:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Client_${{ matrix.platform }}
          path: ${{ needs.build.outputs.build_path }}
      - name: Test run
        run: |
          echo ${{ needs.build.outputs.build_path }}